S2 offset
Open-EO/openeo-geotrellis-extensions pull request #175
Opened 2023-06-19 08:45 UTC by EmileSonneveld

Now band specific. Using metadata.

2023-06-19 13:37 UTC, JeroenVerstraelen requested changes

2023-06-19 13:37 UTC, JeroenVerstraelen commented on openeo-geotrellis/src/main/scala/org/openeo/geotrellis/layers/ValueOffsetRasterSource.scala
> +    rasterSource.reproject(targetCRS, resampleTarget, method, strategy)
Note that when someone uses ValueOffsetRasterSource.reprojection, resample, convert then you don't return a ValueOffsetRasterSource. It's the best to wrap the output of these methods.

2023-06-19 18:33 UTC, EmileSonneveld commented on openeo-geotrellis/src/main/scala/org/openeo/geotrellis/layers/ValueOffsetRasterSource.scala
> +    rasterSource.reproject(targetCRS, resampleTarget, method, strategy)
Good catch! I wrapped them and added tests for it.

2023-06-20 08:41 UTC, JeroenVerstraelen approved these changes

2023-06-20 08:55 UTC, merged