Allow different types SourceName.
Open-EO/openeo-geotrellis-extensions pull request #252
Opened 2023-12-21 09:58 UTC by EmileSonneveld

2023-12-22 14:34 UTC, bossie requested changes
[This commit](https://github.com/Open-EO/openeo-geotrellis-extensions/commit/f69f915f0eae51e53d764985ae8855e6b88e2514) can probably be reverted, right? Because you're handling all kinds of `SourceName` (`case s => s.toString`).

Please add a minimal test case. I wasn't able to find the process graph.

2023-12-22 14:34 UTC, bossie commented on openeo-geotrellis/src/main/scala/org/openeo/geotrellis/layers/FileLayerProvider.scala
> +import geotrellis.raster.{CellSize, CellType, ConvertTargetCellType, CroppedTile, FloatConstantNoDataCellType, FloatConstantTile, GridBounds, GridExtent, MosaicRasterSource, MultibandTile, NoNoData,
`EmptyName` is unused.

2023-12-22 14:34 UTC, bossie commented on openeo-geotrellis/src/main/scala/org/openeo/geotrellis/layers/FileLayerProvider.scala
> +        .flatMap { case (rasterRegion, sourcePath: SourceName) =>
Replace `sourcePath` with `sourceName`.

2023-12-22 14:34 UTC, bossie commented on openeo-geotrellis/src/main/scala/org/openeo/geotrellis/layers/FileLayerProvider.scala
> +            leftValue < rightValue
Can probably be written shorter e.g.

```scala
            def sortable(sourceName: SourceName): String = sourceName match {
              case s: SourcePath => s.value
              case s: StringName => s.value
              case s => s.toString // ex: EmptyName
            }
            sortable(leftSourcePath) < sortable(rightSourcePath)
```

2024-01-03 10:46 UTC, EmileSonneveld commented on openeo-geotrellis/src/main/scala/org/openeo/geotrellis/layers/FileLayerProvider.scala
> +import geotrellis.raster.{CellSize, CellType, ConvertTargetCellType, CroppedTile, FloatConstantNoDataCellType, FloatConstantTile, GridBounds, GridExtent, MosaicRasterSource, MultibandTile, NoNoData,
true, removed

2024-01-03 10:47 UTC, EmileSonneveld commented on openeo-geotrellis/src/main/scala/org/openeo/geotrellis/layers/FileLayerProvider.scala
> +            leftValue < rightValue
implemented as `sortableSourceName`

2024-01-03 10:47 UTC, EmileSonneveld commented on openeo-geotrellis/src/main/scala/org/openeo/geotrellis/layers/FileLayerProvider.scala
> +        .flatMap { case (rasterRegion, sourcePath: SourceName) =>
done

2024-01-03 10:47 UTC, EmileSonneveld commented on openeo-geotrellis/src/main/scala/org/openeo/geotrellis/layers/FileLayerProvider.scala
> +        .flatMap { case (rasterRegion, sourcePath: SourceName) =>
done

2024-01-03 14:55 UTC, EmileSonneveld commented
I added the test process graph as a comment to the ticket

2024-01-03 14:55 UTC, merged