Dateline
Open-EO/openeo-geotrellis-extensions pull request #310
Opened 2024-06-28 10:09 UTC by EmileSonneveld

The issue was an intersection calculation losing a lot of precision due to reprojecting and back

2024-07-22 10:26 UTC, jdries requested changes
Can you also add a test where the feature extent is outside of the valid bounds of target CRS? For instance, a feature with global extent, and target extent being some utm zone.
I think this is the reason for going via EPSG:4326 to compute the intersection safely.

2024-07-25 11:27 UTC, EmileSonneveld commented
Added a test for feature in LatLng and target extent in UTM.
Had to change the code too. This comment describes the change:

> We convert both extents to a common CRS before taking the intersection.
> If one of the CRSes can cover the whole world (non-UTM), this will be used as common CRS.
> We give priority to use the target CRS as common one, because the intersection will be converted to it anyway

2024-08-09 08:49 UTC, EmileSonneveld commented
There where already  many cases where 2 different UTM extentds where used. Confirmed by logging

2024-08-14 10:25 UTC, jdries requested changes
it now assumes that utm is the only projection that has this issue.
EPSG:3035 is another example that we work with a lot.
It could be that the valid area of a crs is in fact available, maybe we can check on that.

2025-02-28 07:36 UTC, jdries commented on openeo-geotrellis/src/main/scala/org/openeo/geotrellis/layers/FileLayerProvider.scala
> +      else targetExtent.crs // Avoid conversion imprecision by intersecting directly in the target CRS
Assuming a method 'isValidExtent(crs,extent:ProjectedExtent)' exists to check if a certain ProjectedExtent is valid in a certain crs exists:

```suggestion
      val commonCrs = if (isValidExtent(targetExtent.crs,featureExtent)) targetExtent.crs
      else if (isValidExtent(feature.crs,targetExtent)) feature.crs.get
      else LatLng
```

2025-02-28 07:47 UTC, jdries commented on openeo-geotrellis/src/main/scala/org/openeo/geotrellis/layers/FileLayerProvider.scala
> +        case None => targetExtent.extent.reproject(targetExtent.crs, targetExtent.crs)
I'm not sure if we should keep this case, can you open a new issue to look into simply discarding the feature when there is no intersection?
Adding a log line could help to reveal if this actually occurs in production, or just an edge case in the code.

2025-02-28 08:51 UTC, EmileSonneveld commented on openeo-geotrellis/src/main/scala/org/openeo/geotrellis/layers/FileLayerProvider.scala
> +        case None => targetExtent.extent.reproject(targetExtent.crs, targetExtent.crs)
Just checked, it gets in this case when an extent gets wrapped badly around the antimeridian after reproject. 
We would be more in control if we double check the project result and wrap it manually if needed
![image](https://github.com/user-attachments/assets/3b1128be-07e4-4d99-8983-7386f00a4788)

2025-02-28 08:57 UTC, EmileSonneveld commented on openeo-geotrellis/src/main/scala/org/openeo/geotrellis/layers/FileLayerProvider.scala
> +        case None => targetExtent.extent.reproject(targetExtent.crs, targetExtent.crs)
Maybe only changing this could be the fix.
The UTM projected to latlon becomes extent is `[-179, 177]`, which is wrong.
It should be represented as:
`[177, 181]` or maybe even `[-183, -179]`
But I guess some code prefers to keep everything within `[-180, 180]`, this would need some extra checking.

2025-02-28 09:21 UTC, EmileSonneveld commented on openeo-geotrellis/src/main/scala/org/openeo/geotrellis/layers/FileLayerProvider.scala
> +      else targetExtent.crs // Avoid conversion imprecision by intersecting directly in the target CRS
Ah, I see. That should be safe indeed. The current implementation assumes that in a request UTM will always be valid when projected to something else, and that a random CRS can not safely be projected to UTM.

Side note: I found that UTM has a huge tolerance for extends that are horizontally outside of their bounds. There were successful jobs where the extent was multiple UTM zones from the correct one and still worked. So an UTM check for validity mostly looks at the vertical coordinates.

2025-03-09 23:14 UTC, merged

2025-03-10 06:42 UTC, jdries commented on openeo-geotrellis/src/main/scala/org/openeo/geotrellis/layers/FileLayerProvider.scala
> +        throw new IllegalArgumentException(s"Feature extent $featureExtentInCommonCRS is invalid in target CRS ${targetExtent.crs}.")
This exception message can be more informative: 
* add process id (load_collection/load_stac)
* add feature id
* use STAC terminology, so 'Item' or 'Asset' instead of 'Feature',

2025-03-10 06:55 UTC, jdries reviewed
Some important comments still, please check!

2025-03-10 06:55 UTC, jdries commented on openeo-geotrellis/src/main/scala/org/openeo/geotrellis/package.scala
> +        logger.warn("healthCheckExtent dangerous extent: " + projectedExtent)
Make this logging more informative towards openEO user. Same as above.
If the purpose of the health check is to avoid using a 'dangerous' extent, than we may also want to avoid alarming the user.

2025-03-10 06:55 UTC, jdries commented on openeo-geotrellis/src/main/scala/org/openeo/geotrellis/layers/FileLayerProvider.scala
> +      else targetExtent.crs // Avoid conversion imprecision by intersecting directly in the target CRS
The final version is still assuming that a target crs that is not UTM is always safe to use?
Please add a test where you use a local reference system like EPSG:3812 and a 'feature' with global bounds.

2025-03-20 08:51 UTC, EmileSonneveld commented on openeo-geotrellis/src/main/scala/org/openeo/geotrellis/layers/FileLayerProvider.scala
> +      else targetExtent.crs // Avoid conversion imprecision by intersecting directly in the target CRS
The latest version does use the isValidExtent trick:
https://github.com/Open-EO/openeo-geotrellis-extensions/blob/9c2ed933a60d6c217675d0c4a333734b93c77270/openeo-geotrellis/src/main/scala/org/openeo/geotrellis/layers/FileLayerProvider.scala#L1441-L1443


readDataCubeWithOpensearchClientUTM has a big LatLon feature (-180.0014880952381, -59.99851190473005, 179.998511906399, 80.00148809523809) where an UTM region is requested. I just added readDataCubeWithOpensearchClientLAEA for good measure.

2025-03-20 08:52 UTC, EmileSonneveld commented on openeo-geotrellis/src/main/scala/org/openeo/geotrellis/layers/FileLayerProvider.scala
> +        case None => targetExtent.extent.reproject(targetExtent.crs, targetExtent.crs)
The latlon warp is avoided by using `safeReproject()`

2025-03-20 08:59 UTC, EmileSonneveld commented on openeo-geotrellis/src/main/scala/org/openeo/geotrellis/layers/FileLayerProvider.scala
> +        throw new IllegalArgumentException(s"Feature extent $featureExtentInCommonCRS is invalid in target CRS ${targetExtent.crs}.")
Reworked to 
`healthCheckExtentAssert(featureExtentInCommonCRS, s"Item extent (${feature.id}) should be valid in common CRS: ")` and `healthCheckExtentAssert(targetExtent, s"Target extent should be valid: ")`

The later will print something like this when it found an issue:
`Target extent should be valid: Extent not within its CRS limits: ProjectedExtent(Extent(649630.0, 1.212245E7, 684180.0, 1.219141E7),EPSG:32631)`

[New PR](https://github.com/Open-EO/openeo-geotrellis-extensions/pull/399/files#diff-891944eb54f3fdfd4e94fc238e95eb5b3817d73b21bc7efa4d95ce3efa44dae2R1429)

For normal usage, I did not see the asserts get triggered tough. They are there just in case. I'll monitor the logs

2025-03-20 09:06 UTC, EmileSonneveld commented on openeo-geotrellis/src/main/scala/org/openeo/geotrellis/layers/FileLayerProvider.scala
> +        case None => targetExtent.extent.reproject(targetExtent.crs, targetExtent.crs)
Also the feature will now get discarded when not intersecting.

2025-03-20 09:07 UTC, EmileSonneveld commented on openeo-geotrellis/src/main/scala/org/openeo/geotrellis/layers/FileLayerProvider.scala
> +        throw new IllegalArgumentException(s"Feature extent $featureExtentInCommonCRS is invalid in target CRS ${targetExtent.crs}.")
I did not find a quick way to log the process id too.  -> added a comment to add this in the future: https://github.com/Open-EO/openeo-geotrellis-extensions/pull/399/commits/24c81c560066b065632bd2542823c09e1f644ea1

2025-03-20 10:19 UTC, EmileSonneveld commented on openeo-geotrellis/src/main/scala/org/openeo/geotrellis/package.scala
> +        logger.warn("healthCheckExtent dangerous extent: " + projectedExtent)
Changed logs to a more user friendly:
`Target extent should be valid: Extent not within its CRS limits: ProjectedExtent(Extent(649630.0, 1.212245E7, 684180.0, 1.219141E7),EPSG:32631)`