Per executor output v02
Open-EO/openeo-geotrellis-extensions pull request #337
Opened 2024-10-18 09:48 UTC by EmileSonneveld

Change for spatial and spatialTemporal cubes. A sync request that loads a single file remains unchanged.
Need to assure sample by feature is tested correctly
Double check if per-date tiffs are written from executor. See if when they have speculative execution, the problem is there too

2024-10-31 11:05 UTC, bossie requested changes
Basic algorithm looks fine, just some remarks to tidy up the code.

2024-10-31 11:05 UTC, bossie commented on geotrellis-extensions/src/test/scala/org/openeo/extensions/PyramidFactoryTest.scala
> +@Disabled("Avoid 'You have exceeded your rate limit'")
Enable again.

2024-10-31 11:05 UTC, bossie commented on geotrellis-sentinelhub/src/test/scala/org/openeo/geotrellissentinelhub/PyramidFactoryTest.scala
> +@Disabled("Avoid 'You have exceeded your rate limit'")
Enable again. I've created #342 to look into this.

2024-10-31 11:05 UTC, bossie commented on openeo-geotrellis/src/test/scala/org/openeo/geotrellis/geotiff/TileGridTest.scala
> +import better.files.File.apply
Remove unused import.

2024-10-31 11:05 UTC, bossie commented on openeo-geotrellis/src/test/scala/org/openeo/geotrellis/geotiff/TileGridTest.scala
> +    Files.createDirectories(outDir)
Port this test to JUnit 5 (Jupiter) and use `@TempDir` (see elsewhere in the code for examples).

2024-10-31 11:05 UTC, bossie commented on openeo-geotrellis/src/test/scala/org/openeo/geotrellis/geotiff/WriteRDDToGeotiffTest.scala
> +    Files.createDirectories(outDir)
See above, use `@TempDir` everywhere to avoid having to delete stuff.

2024-10-31 11:05 UTC, bossie commented on openeo-geotrellis/src/test/scala/org/openeo/geotrellis/layers/FileLayerProviderTest.scala
> +    Files.createDirectories(Paths.get("tmp/"))
Use `@TempDir`.

2024-10-31 11:05 UTC, bossie commented on openeo-geotrellis/src/main/scala/org/openeo/geotrellis/geotiff/package.scala
> +      Files.createDirectories(base)
Instead of `base`, call it `executorAttemptDirectory`.

Extract this logic into a method and use it elsewhere e.g.

```scala
private def createExecutorAttemptDirectory(parentDirectory: Path): Path = {
  // add comment that explains why this is needed
  // create the unique directory and returns it as a Path
  // avoid the generic "tmp" prefix and use e.g. "executorAttempt"
}
```

2024-10-31 11:05 UTC, bossie commented on openeo-geotrellis/src/main/scala/org/openeo/geotrellis/geotiff/package.scala
> +    }.collect().map({
Avoid unnecessary parentheses i.e. just `.map {`.

2024-10-31 11:05 UTC, bossie commented on openeo-geotrellis/src/main/scala/org/openeo/geotrellis/geotiff/package.scala
> +      case (absolutePath, timestamp, croppedExtent, bandIndices) =>
```suggestion
      case (absoluteFilePath, timestamp, croppedExtent, bandIndices) =>
```

Rename others as well.

2024-10-31 11:05 UTC, bossie commented on openeo-geotrellis/src/main/scala/org/openeo/geotrellis/geotiff/package.scala
> +        val destinationPath = Path.of(path).resolve(relativePath.substring(relativePath.indexOf("/") + 1))
Avoid string manipulation and call `relativePath.getParent()`

But rename `relativePath` to `relativeFilePath` as well.

2024-10-31 11:05 UTC, bossie commented on openeo-geotrellis/src/main/scala/org/openeo/geotrellis/geotiff/package.scala
> +    }
Extract into method e.g. extract method `deleteUnusedExecutorAttemptDirectories(parentDirectory: Path)`.

Put the common prefix (in this case "tmp") into a constant and refer to it from `createExecutorAttemptDirectory` (see above).

2024-10-31 11:05 UTC, bossie commented on openeo-geotrellis/src/main/scala/org/openeo/geotrellis/geotiff/package.scala
> +            base + name
call `createExecutorAttemptDirectory` (see above).

2024-10-31 11:05 UTC, bossie commented on openeo-geotrellis/src/main/scala/org/openeo/geotrellis/geotiff/package.scala
> +      }.collect().map({
Remove the unnecessary parentheses.

2024-10-31 11:05 UTC, bossie commented on openeo-geotrellis/src/main/scala/org/openeo/geotrellis/geotiff/package.scala
> +        case (absolutePath, y) =>
```suggestion
        case (absolutePath, bandIndices) =>
```

2024-10-31 11:05 UTC, bossie commented on openeo-geotrellis/src/main/scala/org/openeo/geotrellis/geotiff/package.scala
> +            val destinationPath = beforeOut + relativePath.substring(relativePath.indexOf("/") + 1)
Avoid string manipulation and call `relativePath.getParent()` (see above).

2024-10-31 11:05 UTC, bossie commented on openeo-geotrellis/src/main/scala/org/openeo/geotrellis/geotiff/package.scala
> +      }
call `deleteUnusedExecutorAttemptDirectories` (see above).

2024-10-31 11:05 UTC, bossie commented on openeo-geotrellis/src/main/scala/org/openeo/geotrellis/geotiff/package.scala
> +      }
Same remark re: calling dedicated methods `createExecutorAttemptDirectory` and `deleteUnusedExecutorAttemptDirectories`.

2024-10-31 11:07 UTC, bossie commented
I'm not sure what happens if `collect` returns before competing executors have all finished; I suppose some files don't get cleaned up?

Java has a way to clean up temp files upon JVM exit that we could look into if needed (that would be a separate issue).

2024-10-31 11:28 UTC, bossie commented
I also think that this only works if the batch job bucket is mounted because AFAICT you're treating every path as a file on disk.

2024-10-31 16:26 UTC, EmileSonneveld commented on geotrellis-extensions/src/test/scala/org/openeo/extensions/PyramidFactoryTest.scala
> +@Disabled("Avoid 'You have exceeded your rate limit'")
re-enabled

2024-10-31 16:28 UTC, EmileSonneveld commented on openeo-geotrellis/src/main/scala/org/openeo/geotrellis/geotiff/package.scala
> +      }
Moved the functionality to 3 functions: `createExecutorAttemptDirectory`, `moveFromExecutorAttemptDirectory` and `cleanUpExecutorAttemptDirectory`

2024-10-31 16:37 UTC, EmileSonneveld commented on geotrellis-sentinelhub/src/test/scala/org/openeo/geotrellissentinelhub/PyramidFactoryTest.scala
> +@Disabled("Avoid 'You have exceeded your rate limit'")
re-enabled

2024-10-31 16:38 UTC, EmileSonneveld commented on openeo-geotrellis/src/test/scala/org/openeo/geotrellis/geotiff/TileGridTest.scala
> +import better.files.File.apply
removed multiple unused imports

2024-10-31 16:45 UTC, EmileSonneveld commented
`collect` should launch the executors and wait till they are finished.
I'll see if I can test without a mounted s3 bucket. 
This trick is implemented to avoid an issue we only had with fusemounts, but I think it makes sense to keep it even with direct S3 access, as it avoids a racing condition.

2024-10-31 17:09 UTC, bossie commented
> `collect` should launch the executors and wait till they are finished.

Yes, but speculative execution launches additional redundant executors and I should hope that `collect` does not wait for the slow ones.

2024-11-05 09:26 UTC, EmileSonneveld commented on geotrellis-sentinelhub/src/test/scala/org/openeo/geotrellissentinelhub/BatchProcessingServiceTest.scala
> +@Ignore("Avoid SentinelHubException in CI")
I'll re-enable at time of merging

2024-11-05 11:07 UTC, EmileSonneveld commented on openeo-geotrellis/src/main/scala/org/openeo/geotrellis/geotiff/package.scala
> +            val destinationPath = beforeOut + relativePath.substring(relativePath.indexOf("/") + 1)
It does something different thatn getParent.
I added a comment:
`// Remove the executorAttemptDirectory part from the path`

2024-11-07 13:59 UTC, EmileSonneveld commented
Speculative execution seems to kill remaining attempts when one succeeded: `killed: another attempt succeeded`
`cleanUpExecutorAttemptDirectory` handles their partial written files

2024-11-07 13:59 UTC, EmileSonneveld commented
- This is tested with writing to standard files in the Scala code. (WriteRDDToGeotiffTest and others) 
- And tested with s3 output here: https://github.com/Open-EO/openeo-geopyspark-driver/blob/master/tests/deploy/test_batch_job.py#L1309
- Once gone trough CDSE integration tests, it is best to re-run the tests with fusemount disabled on CDSE dev.

2024-11-07 14:01 UTC, merged